export const listBrand = [
  { id: 1, title: "a2", img: "assest/images/banner/a2.png", atl: "a2 Milk" },
  {
    id: 2,
    title: "Aptamil",
    img: "assest/images/banner/aptamil.png",
    atl: "Aptamil",
  },
  {
    id: 3,
    title: "Bellamy",
    img: "assest/images/banner/bellamy.png",
    atl: "Bellamy",
  },
  {
    id: 4,
    title: "Enfamil",
    img: "assest/images/banner/enfa.png",
    atl: "Enfamil",
  },
  {
    id: 5,
    title: "ensure",
    img: "assest/images/banner/ensure.png",
    atl: "Ensure",
  },
  {
    id: 6,
    title: "Friso Gold Pro",
    img: "assest/images/banner/Friso.png",
    atl: "Friso Gold Pro",
  },
  {
    id: 7,
    title: "growGold",
    img: "assest/images/banner/growGold.png",
    atl: "Abbot Grow",
  },
  {
    id: 8,
    title: "nutifood",
    img: "assest/images/banner/nutifood.png",
    atl: "nutifood",
  },
  {
    id: 9,
    title: "Vinamilk",
    img: "assest/images/banner/vinamilk.png",
    atl: "Vinamilk",
  },
  {
    id: 10,
    title: "Vanma (Nutifood)",
    img: "assest/images/banner/varna.png",
    atl: "Vanma (Nutifood)",
  },
  {
    id: 11,
    title: "Fanma (Nutifood)",
    img: "assest/images/banner/famma.png",
    atl: "Fanma (Nutifood)",
  },
  {
    id: 12,
    title: "Hikid",
    img: "assest/images/banner/hikid.png",
    atl: "Hikid",
  },
  {
    id: 13,
    title: "anutricia",
    img: "assest/images/banner/nutricia.png",
    atl: "nutricia",
  },
  {
    id: 14,
    title: "Similac",
    img: "assest/images/banner/similac.png",
    atl: "Similac",
  },
  {
    id: 15,
    title: "Wakodo",
    img: "assest/images/banner/wakado.png",
    atl: "Wakodo",
  },
  {
    id: 16,
    title: "Yoko Gold",
    img: "assest/images/banner/yokoGold.png",
    atl: "Yoko Gold",
  },
];
